version: '3.7'
services:
  db:
    image: mysql:8.1
    container_name: banco_mysql
    volumes:
      - ./:/home

    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'empresa'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'q1w2e3r4'
      MYSQL_ROOT_PASSWORD: 'q1w2e3r4'
